### ISSUE TITLE
invalid requirement syntax

### ISSUE THREAD

**Issue by glelouet** [alien4cloud/tosca-normative-types#1]
requirements in tosca specification is eg

```
  requirements:
    - database:
        node: my_database
        capability: Endpoint.Database
        relationship: my.types.CustomDbConnection
```

in this yaml file it is 

```
    requirements:
      - host: tosca.capabilities.Container
        relationship: tosca.relationships.HostedOn
```

however this syntax is invalid. It should instead be

```
    requirements:
      - host:
          capability: tosca.capabilities.Container
          relationship: tosca.relationships.HostedOn
```
